### ISSUE TITLE
unique on ip and deviceid

### ISSUE THREAD

**Issue by TradeFace** [TradeFace/gismocaster#34]

**Comment by emontnemery** [comment]
Do you mean you will base unique_id on ip and deviceid?
I think IP change should be allowed?

**Comment by TradeFace** [comment]
Nope, just unique per column. Both can be changed as long as they are unique in the system. (to prevent double thread starts) Also considering trying to enforce uniqueness in mqtt. i.e. a check if GC is the "owner" of the topic and the ip/deviceid
