### ISSUE TITLE
using smart socket to measure power consumption

### ISSUE THREAD

**Issue by kenodressel** [TradeFace/gismocaster#50]
I am having troubles setting up a smart socket. I got the whole setup working with tuyagateway etc and can turn the switch on and off. Now I am looking into power consumption and have troubles warpping my head around `gismos` and `gismo models` to forward the data to home assistant.

**Comment by TradeFace** [comment]
A gismo (device) is an instance of a gismo model. If you have multiple devices of the same type, you can reuse the model (and thus only need to create a new gismo) 

The gismomodel is linked to a HA component type. The HA component holds the definition of which options are available (and sets some defaults) for a component. So, you'll have to select the right component that has the ability to send the power info to HA (not sure which one that would be) and linke the datapoint that holds the power data to the publish topic. 

BTW tuyagateway will send all returned data on the attributes topic (if you can't solve it with the above info)

**Comment by kenodressel** [comment]
Okay I think I understand now. I will have to further experiment with the setup. Thanks for the quick reply anyways :)
