### ISSUE TITLE
Docker Install Not Working

### ISSUE THREAD

**Issue by djtimca** [TradeFace/gismocaster#51]
Here is what I am getting:

'administrator@hass-pc:~/gismocaster$ sudo docker run -it --rm --name my-app gismocaster
python: can't open file './web/manage.py runserver 0.0.0.0:8000 --noreload': [Errno 2] No such file or directory
administrator@hass-pc:~/gismocaster$'

**Comment by TradeFace** [comment]
Thanks for your report. I'll have to look into it.

**Comment by djtimca** [comment]
OK - got it running. Had to change Dockerfile to the following (running Portainer which uses port 8000.

```
FROM python:3.6

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
RUN make

EXPOSE 8500

CMD python3 web/manage.py runserver 0.0.0.0:8500 --noreload

```

**Comment by TradeFace** [comment]
Great! Probably a good idea to move away from the standard python port. Thanks for the feedback
