### ISSUE TITLE
MQTT settings not imported

### ISSUE THREAD

**Issue by borpin** [TradeFace/gismocaster#58]
I have manually edited the file `web/mqtt/fixtures/setting.json` but it seems it is not imported.

on start
```
WARNING  [mqtt.mqtt] () Failed to connect to MQTT Broker Setting matching query does not exist.
```
This is generated when this line is executed;

https://github.com/TradeFace/gismocaster/blob/82569ae590a8ca11e66ea92f5c048e06960e687e/web/mqtt/mqtt.py#L339

And the MQTT settings never appear in the webUI.

**Comment by TradeFace** [comment]
please rerun installation... all fixtures are imported on install.
